default:
  image: draabat/laravel-deployer:0.0.1
#  services:
#    - mysql:5.7

before_script:
  - echo "$DEPLOYER_HOSTS" > deployer-hosts.yaml
  - echo "$DEPLOY_PHP" > deploy.php
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#variables:
#  MYSQL_DATABASE: homestead
#  MYSQL_ROOT_PASSWORD: secret
#  DB_HOST: mysql
#  DB_USERNAME: root

stages:
  - test
  - deploy

#unit_test:
#  stage: test
#  script:
#    - cp .env.example .env
#    - composer install
#    - php artisan key:generate
#    - php artisan migrate
#    - vendor/bin/phpunit

deploy_test:
  stage: deploy
  script:
    - ~/.composer/vendor/bin/dep deploy test --commit="$CI_COMMIT_SHA"
  environment:
    name: test
    url: https://test.mv-kematen.at
  when: manual

deploy_production:
  stage: deploy
  script:
    - ~/.composer/vendor/bin/dep deploy production --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: https://intern.mv-kematen.at
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
