default:
  image: draabat/laravel-deployer:0.0.4
#  services:
#    - mysql:5.7

before_script:
  - eval $(ssh-agent -s)
  # Generate the private/public key pair using:
  #
  #     ssh-keygen -f deploy_key -N ""
  #
  # then set the $SSH_PRIVATE_KEY environment variable in the CI (Travis-CI,
  # GitLab-CI, ...) to the base64 encoded private key:
  #
  #     cat deploy_key | base64 -w0
  #
  # and add the public key `deploy_key.pub` into the target git repository (with
  # write permissions).
  - ssh-add <(echo "${SSH_PRIVATE_KEY}")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#variables:
#  MYSQL_DATABASE: homestead
#  MYSQL_ROOT_PASSWORD: secret
#  DB_HOST: mysql
#  DB_USERNAME: root

stages:
  - build
  - test
  - deploy

build_assets:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - public/build/
  script:
    - npm install
    - npm run build

build_tests:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - /
  script:
    - composer install

unit_test:
  stage: test
  needs: ["build_tests"]
  only:
    - tags
  dependencies:
    - build_tests
  script:
    - artisan test --filter unit

pint_test:
  stage: test
  needs: ["build_tests"]
  only:
    - tags
  dependencies:
    - build_tests
  script:
    - ./vendor/bin/pint --test

deploy_test:
  stage: deploy
  dependencies:
    - build_assets
  script:
    - echo "${DEPLOYER_HOSTS}" > deployer-hosts.yaml
    - echo "${DEPLOY_PHP}" > deploy.php
    - ~/.config/composer/vendor/bin/dep deploy test --tag="$CI_COMMIT_TAG"
  environment:
    name: test
    url: https://clubmanager.softdev.at
  rules:
    - when: manual

deploy_production:
  stage: deploy
  dependencies:
    - build_assets
  script:
    - echo "${DEPLOYER_HOSTS}" > deployer-hosts.yaml
    - echo "${DEPLOY_PHP}" > deploy.php
    - ~/.config/composer/vendor/bin/dep deploy production --tag="$CI_COMMIT_TAG"
  environment:
    name: production
    url: https://intern.mv-kematen.at
  rules:
    - if: '$CI_COMMIT_TAG && ($CI_COMMIT_TAG =~ /^v?\d+(.\d+){0,3}$/ )'
      when: manual
    - when: never
